-- RK Mines Diesel Ledger
-- Run this once in the Supabase SQL Editor for the connected project.

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  vehicle_no text not null unique,
  vehicle_name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.staff_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null check (role in ('operator', 'issuer')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (name, role)
);

create table if not exists public.diesel_records (
  id bigint generated by default as identity primary key,
  date date not null,
  vehicle_id bigint not null references public.vehicles(id),
  opening_balance numeric(12, 2) not null default 0,
  reading numeric(12, 2),
  diesel_issued numeric(12, 2) not null default 0,
  diesel_purchased numeric(12, 2) not null default 0,
  closing_balance numeric(12, 2) not null default 0,
  operator text not null,
  issuer text not null,
  created_at timestamptz not null default now()
);

create index if not exists diesel_records_date_idx
  on public.diesel_records (date, created_at, id);

create index if not exists diesel_records_vehicle_idx
  on public.diesel_records (vehicle_id);

alter table public.vehicles enable row level security;
alter table public.staff_members enable row level security;
alter table public.diesel_records enable row level security;

drop policy if exists "authenticated users can manage vehicles" on public.vehicles;
create policy "authenticated users can manage vehicles"
  on public.vehicles for all to authenticated using (true) with check (true);

drop policy if exists "authenticated users can manage staff" on public.staff_members;
create policy "authenticated users can manage staff"
  on public.staff_members for all to authenticated using (true) with check (true);

drop policy if exists "authenticated users can manage diesel records" on public.diesel_records;
create policy "authenticated users can manage diesel records"
  on public.diesel_records for all to authenticated using (true) with check (true);

-- Starter fleet. Existing vehicle numbers are left untouched.
insert into public.vehicles (vehicle_no, vehicle_name)
values
  ('EX-07', 'Excavator 07'),
  ('DT-12', 'Dump Truck 12')
on conflict (vehicle_no) do nothing;

-- Add real names to the dropdowns, for example:
-- insert into public.staff_members (name, role) values
--   ('Operator Name', 'operator'), ('Issuer Name', 'issuer')
-- on conflict (name, role) do nothing;

-- Optional opening stock entry for the first working day.
insert into public.diesel_records (
  date, vehicle_id, opening_balance, reading, diesel_issued,
  diesel_purchased, closing_balance, operator, issuer
)
select
  current_date, id, 0, null, 0, 1200, 1200, 'System opening', 'Store desk'
from public.vehicles
where vehicle_no = 'EX-07'
  and not exists (
    select 1 from public.diesel_records where date = current_date
  );

-- The current app has no login screen, so keep these tables without RLS
-- until Clerk/authentication is added. If you enable RLS later, add
-- authenticated-user policies before switching it on.