-- Rajsthan M&M Diesel Ledger
-- Run this once in the Supabase SQL Editor for the connected project.

create table if not exists public.vehicles (
  id bigint generated by default as identity primary key,
  vehicle_no text not null unique,
  vehicle_name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.staff_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null check (role in ('operator', 'issuer')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (name, role)
);

create table if not exists public.diesel_records (
  id bigint generated by default as identity primary key,
  date date not null,
  vehicle_id bigint not null references public.vehicles(id),
  opening_balance numeric(12, 2) not null default 0,
  reading numeric(12, 2),
  diesel_issued numeric(12, 2) not null default 0,
  diesel_purchased numeric(12, 2) not null default 0,
  closing_balance numeric(12, 2) not null default 0,
  operator text not null,
  issuer text not null,
  created_at timestamptz not null default now()
);

create index if not exists diesel_records_date_idx
  on public.diesel_records (date, created_at, id);

create index if not exists diesel_records_vehicle_idx
  on public.diesel_records (vehicle_id);

alter table public.vehicles enable row level security;
alter table public.staff_members enable row level security;
alter table public.employees enable row level security;
alter table public.dropdown_categories enable row level security;
alter table public.diesel_records enable row level security;

create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  name text not null,
  role text not null check (role in ('operator', 'issuer')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (name, role)
);

create table if not exists public.dropdown_categories (
  id text primary key,
  description text not null unique,
  options jsonb not null default '[]'::jsonb,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop policy if exists "authenticated users can manage vehicles" on public.vehicles;
create policy "authenticated users can manage vehicles"
  on public.vehicles for all to authenticated using (true) with check (true);

drop policy if exists "authenticated users can manage staff" on public.staff_members;
create policy "authenticated users can manage staff"
  on public.staff_members for all to authenticated using (true) with check (true);

drop policy if exists "authenticated users can manage employees" on public.employees;
create policy "authenticated users can manage employees"
  on public.employees for all to authenticated using (true) with check (true);

drop policy if exists "authenticated users can manage dropdown_categories" on public.dropdown_categories;
create policy "authenticated users can manage dropdown_categories"
  on public.dropdown_categories for all to authenticated using (true) with check (true);

drop policy if exists "allow anon to read dropdown_categories" on public.dropdown_categories;
create policy "allow anon to read dropdown_categories"
  on public.dropdown_categories for select to anon using (true);

drop policy if exists "authenticated users can manage diesel records" on public.diesel_records;
create policy "authenticated users can manage diesel records"
  on public.diesel_records for all to authenticated using (true) with check (true);

-- Starter fleet. Existing vehicle numbers are left untouched.
insert into public.vehicles (vehicle_no, vehicle_name)
values
  ('EX-07', 'Excavator 07'),
  ('DT-12', 'Dump Truck 12')
on conflict (vehicle_no) do nothing;

-- Starter employees and staff members
insert into public.employees (name, role, active)
values
  ('Ramesh Singh', 'operator', true),
  ('Suresh Kumar', 'operator', true),
  ('Vikram Rathore', 'operator', true),
  ('Mahesh Sharma', 'issuer', true),
  ('Rajesh Meena', 'issuer', true)
on conflict (name, role) do nothing;

insert into public.staff_members (name, role, active)
values
  ('Ramesh Singh', 'operator', true),
  ('Suresh Kumar', 'operator', true),
  ('Vikram Rathore', 'operator', true),
  ('Mahesh Sharma', 'issuer', true),
  ('Rajesh Meena', 'issuer', true)
on conflict (name, role) do nothing;

-- Starter dropdown matrix categories and options
insert into public.dropdown_categories (id, description, options, sort_order)
values
  ('vehicle-type', 'Vehicle Type', '["JCB", "Dumper", "Trailor", "Car", "Excavator", "Tanker", "Tractor", "Loader", "Hydra Crane", "Forklift", "Other Vehicle", "Truck", "Tata Yodha"]'::jsonb, 1),
  ('maintenance-status', 'Maintenance Status', '["Active (Running)", "Under Maintenance", "Breakdown", "Not installed"]'::jsonb, 2),
  ('permit-type', 'Permit Type', '["State Permit", "National Permit", "Mines Internal Only", "Not Applicable (Private)"]'::jsonb, 3),
  ('gps-status', 'GPS Status', '["Installed (Working)", "Not Working / Issue", "No GPS Installed"]'::jsonb, 4),
  ('camera-status', 'Camera Status', '["Installed (Working)", "Not Working / Issue", "No Camera Installed"]'::jsonb, 5)
on conflict (id) do nothing;

-- Optional opening stock entry for the first working day.
insert into public.diesel_records (
  date, vehicle_id, opening_balance, reading, diesel_issued,
  diesel_purchased, closing_balance, operator, issuer
)
select
  current_date, id, 0, null, 0, 1200, 1200, 'System opening', 'Store desk'
from public.vehicles
where vehicle_no = 'EX-07'
  and not exists (
    select 1 from public.diesel_records where date = current_date
  );

-- The current app has no login screen, so keep these tables without RLS
-- until Clerk/authentication is added. If you enable RLS later, add
-- authenticated-user policies before switching it on.